name: pintersest_clone
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+2
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  http: ^0.12.1
  equatable: ^1.1.1
  flutter_inappwebview: ^3.3.0+3
  flutter_staggered_grid_view: ^0.3.0
  shared_preferences: ^0.5.7+3
  email_validator: '^1.0.0'


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^5.0.0
  mockito: ^4.1.1
  pedantic_mono: any
  flutter_driver:
    sdk: flutter
  test: any


flutter:

  uses-material-design: true

  assets:
    - assets/images/

